### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Apply https://github.com/gtk-rs/gir/pull/426

### CODE REVIEW

**Comment by EPashkin** [comment]
..and ignore clippy warnings in generated code.

**Comment by EPashkin** [comment]
cc @GuillaumeGomez, @sdroege

**Comment by sdroege** [comment]
Looks good, assuming the constructor really can't return NULL :)

Before regening gtk/go, I want to add the trait rename config for GtkApplication later today.

**Comment by EPashkin** [comment]
@sdroege I thought that trait renaming don't affect gtk-rs, so already added PR for gio. It better wait until you add renaming?

**Comment by sdroege** [comment]
Worst case we regenerate again :)

The conflict in gtk/gio is ApplicationExt

**Comment by EPashkin** [comment]
I think it conflict only with gstreamer, then I change https://github.com/gtk-rs/gio/pull/48 to WIP

**Comment by EPashkin** [comment]
About `coverage::new`: from https://developer.gnome.org/gobject/stable/howto-gobject-construction.html

>It is important to note that object construction cannot ever fail. If you require a fallible GObject construction, you can use the GInitable and GAsyncInitable interfaces provided by the GIO library.

**Comment by sdroege** [comment]
No, conflict with gstreamer is ObjectExt from glib. The other conflict is between gio and gtk, ApplicationExt.

The one further "down" should be renamed, I.e. GtkApplicationExt and GstObjectExt.

**Comment by EPashkin** [comment]
> The one further "down" should be renamed, I.e. GtkApplicationExt and GstObjectExt.

That make sense.
@GuillaumeGomez you agree?

**Comment by GuillaumeGomez** [comment]
I agree.

**Comment by GuillaumeGomez** [comment]
So is this one ready yet or not?

**Comment by EPashkin** [comment]
Yes, ready, we discussed PRs in gtk and gio.

**Comment by GuillaumeGomez** [comment]
Ok, thanks then!

**Pull request merged**
