### PR TITLE
groovy update: regenerate

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Looks good to me, can go in after the `gir-files` PR is in. Thanks!

**Comment by sdroege** [comment]
@bilelmoussaoui Please regenerate with the merged version of `gir-files` and then let's get it in :)

**Comment by bilelmoussaoui** [comment]
Done! 
I have noticed an issue though, the PartialEq implementation for AttrList should be hidden behind a feature flag the same as the equal method
```
rList` in the current scope
   --> src/auto/attr_list.rs:107:14
    |
107 |         self.equal(other)
    |              ^^^^^ method not found in `&auto::attr_list::AttrList`

```
Not sure how to achieve that properly?

**Comment by bilelmoussaoui** [comment]
> Done!
> I have noticed an issue though, the PartialEq implementation for AttrList should be hidden behind a feature flag the same as the equal method
> 
> ```
> rList` in the current scope
>    --> src/auto/attr_list.rs:107:14
>     |
> 107 |         self.equal(other)
>     |              ^^^^^ method not found in `&auto::attr_list::AttrList`
> ```
> 
> Not sure how to achieve that properly?

I have generated the equal function manually, should be good

**Review by sdroege — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
