### PR TITLE
Pango layout wrapper

### PR DESCRIPTION
**Pull request by Britefury**
Added pango_layout_\* functions to pango-sys.
Implemented wrapper structs for PangoContext and PangoLayout.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for your work ! And sorry but your PR arrived at the worst moment. We're changing a lot of things today (for example, all sys are now in one repo). It should be good again in a few hours.

**Comment by gkoz** [comment]
Like @GuillaumeGomez said, the `pango` crate now uses [this sys crate](https://github.com/rust-gnome/sys/tree/master/pango-sys) that shouldn't need any manual input anymore. (There's a little issue of documenting enum values but that will have to be done with newtypes.)

The `widgets` module doesn't make sense here, it's a relic of rgtk so just put all modules in the root.

Since `PangoContext` is ` GObject` I'd recommend following the same convention the `gdk` crate does: a [generic object struct](https://github.com/rust-gnome/gdk/blob/master/src/object.rs) and typedefs, like in https://github.com/rust-gnome/gdk/blob/master/src/device_manager.rs. You can also see that null pointer checking is already handled by the `FromGlibPtr` impl, so no `if`s are needed. Also note that usually constructors don't return `NULL`s so no `Option` for them.

The trivial casts `i32 as c_int` and `c_int as i32` and explicit variable types (`let mut x: i32 = 0`) are redundant.

The booleans are converted with `from_glib` function and `to_glib` method (and the enum newtypes would be as well).

**Comment by gkoz** [comment]
Be advised that manually implementing these bindings will in significant part be obsoleted by the [gir](https://github.com/gkoz/gir) project (that's what generates the sys crates).

**Comment by Britefury** [comment]
I have rebased off the current master today. The changes to `sys` are gone as they are obsolete as you pointed out.
It seems the compilation failure may be due to a GTK version incompatibility.

**Comment by GuillaumeGomez** [comment]
Weird, they should be in the lib... @gkoz the generation doesn't include them ? It doesn't seem a special version of pango (1.32) is needed here.

**Comment by gkoz** [comment]
Looks like the failing functions need to have the appropriate `cfg` directives (e.g. `#[cfg(pango_1_32_4)]` for `get_serial`. Alas there's nothing setting those directives in this crate so it will need a build script similar to [this one](https://github.com/gtk-rs/gdk/blob/master/build.rs) included [like this](https://github.com/gtk-rs/gdk/blob/master/Cargo.toml#L5).

**Comment by gkoz** [comment]
Also the above comments still apply but this time the generator is in a pretty good shape so you might want to try generating `Context`, `Layout` and other `GObject`s with it.

**Pull request closed without merging**
