### PR TITLE
Bring Travis and AppVeyor configurations in sync with the GLib one

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
```
$ git diff -R --exit-code
diff --git b/src/prelude.rs a/src/prelude.rs
index 11c1e19..185fc02 100644
--- b/src/prelude.rs
+++ a/src/prelude.rs
@@ -2,4 +2,6 @@
 // See the COPYRIGHT file at the top-level directory of this distribution.
 // Licensed under the MIT license, see the LICENSE file or <http://opensource.org/licenses/MIT>
 
+//! Traits and essential types inteded for blanket imports.
+
 pub use auto::traits::*;
The command "git diff -R --exit-code" exited with 1.
```

What to do about this?

**Comment by GuillaumeGomez** [comment]
Oh it removes things from `lib.rs`? Hmmmm... Not sure what the good thing to do would be in here...

**Comment by sdroege** [comment]
How is this handled in other crates?

**Comment by GuillaumeGomez** [comment]
Is there such a case in any other crates?

**Comment by EPashkin** [comment]
@GuillaumeGomez strange that it touch `lib.rs` it in IGNORES

**Comment by EPashkin** [comment]
Hm, I made mistake again, "prelude.rs" not in IGNORES

**Comment by GuillaumeGomez** [comment]
Mystery solved! :3

**Comment by sdroege** [comment]
What `IGNORES`?

**Comment by sdroege** [comment]
Ah I see.

**Comment by EPashkin** [comment]
👍

**Comment by sdroege** [comment]
@GuillaumeGomez green

**Pull request merged**
