### PR TITLE
Fixes pango_layout_xy_to_index and FontMap trait

### PR DESCRIPTION
**Pull request by EPashkin**
Closes https://github.com/gtk-rs/pango/issues/62
Part of https://github.com/gtk-rs/gir/issues/351

### CODE REVIEW

**Comment by EPashkin** [comment]
@RazrFalcon @jgillich Please take look at this changes.

**Comment by jgillich** [comment]
Did you mean to ping someone else? I haven't touched gtk-rs in a looong time. :)

**Comment by EPashkin** [comment]
@jgillich Sorry, I mean @johncf

**Comment by johncf** [comment]
@EPashkin Looks great! Thanks!

I'm guessing this new change will also allow `pangocairo::FontMap` to be "sub-classed" from `pango::FontMap`, right?

**Comment by EPashkin** [comment]
@johncf Yes

**Comment by johncf** [comment]
@EPashkin Great! I'll see what needs to be done after a few days... (I'm running very low on time right now...)

**Comment by EPashkin** [comment]
As no one against it, this PR ready for merge

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
