### PR TITLE
Switch CI to master branch of the examples

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/examples/issues/285

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Pango don't have stable travis check so no regen_check called.
What better to do: add it or just change regen_check to `1.39.0` or `beta`?

**Comment by GuillaumeGomez** [comment]
Add the regen_check for `1.39` I'd say. Or even better: change it for stable.

**Comment by EPashkin** [comment]
> Or even better: change it for stable.

IMHO removing 1.39 completely not goo, maybe just add one test on stable (and make it first to call rege_check earlier)

**Comment by GuillaumeGomez** [comment]
We're supposed to have a test targetting stable.

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
