### PR TITLE
Regenerate autogenerated bindings with latest GIR

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by EPashkin** [comment]
Strange, we have 2 matrix.rs: generated and manual. As currently we don't have generated PangoRectangle, IMHO better ignore this.
@GuillaumeGomez 👍 for merge.
Thanks, @sdroege

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by sdroege** [comment]
AFAIU from https://github.com/gtk-rs/gtk/pull/509#issuecomment-301445891 , I'd have to add a prelude and export all the traits from there still. Comes next

**Comment by EPashkin** [comment]
@GuillaumeGomez, can we move all modules from https://github.com/gtk-rs/pango/tree/master/src/widgets to `/src` ?

**Comment by GuillaumeGomez** [comment]
Yes, I don't think we need to keep this split.

**Pull request merged**
